### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by NoriakiHoriuchi**
updated sbt, H2, Logback, Scala, Skinny-ORM, and ScalikeJDBC.

### CODE REVIEW

**Comment by xuwei-k** [comment]
```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::              FAILED DOWNLOADS            ::
[warn]  :: ^ see resolution messages for details  ^ ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.skinny-framework#skinny-orm_2.10;1.3.20!skinny-orm_2.10.jar
[warn]  :: org.skinny-framework#skinny-common_2.10;1.3.20!skinny-common_2.10.jar
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: download failed: org.skinny-framework#skinny-orm_2.10;1.3.20!skinny-orm_2.10.jar
```

I think we should
- add `fullResolvers ~= {_.filterNot(_.name == "jcenter")}` setting
- or use sbt 0.13.8
- or report issue to jcenter

**Comment by seratch** [comment]
Thanks. Since skinny-\* 1.3.20 are surely available on the Maven central repos, this should be a jcenter's issue. I just [pinged](https://twitter.com/ScalikeJDBC/status/647603223658819585) scala_sbt on Twitter. If the jcenter issue won't be resolved immediately, using 0.13.8 for now with a link for this issue would be OK.

**Comment by seratch** [comment]
I found we should update .travis.yml too. Currently we're checking only builds in 2.10.3.

**Comment by xuwei-k** [comment]
https://gitter.im/scalajp/public?at=55cc05c23d8917890c15c79c

> 意図した挙動です。不味いようだったらバグってる module id を報告して下さい。

**Comment by eed3si9n** [comment]
ご迷惑おかけしています。
In sbt/sbt#2217 JFrog person says that they've been under DDOS attack during 18th-21st so there's been higher error rates. Please report any issues to both sbt/sbt#2217 and JFrog. In the meantime, we might release a new version that reverts the default resolver back to Maven Central.

**Comment by seratch** [comment]
@eed3si9n どうもありがとうございます。I understand what the cause of this issue is.
@NoriakiHoriuchi I just reran the jobs, but they're still failing. Would you revert sbt version to 0.13.8 when you have time?

**Comment by NoriakiHoriuchi** [comment]
Passed.  I really appreciate your cooperation.

**Comment by xuwei-k** [comment]
> I found we should update .travis.yml too. Currently we're checking only builds in 2.10.3.

does not update yet `.travis.yml`

**Comment by NoriakiHoriuchi** [comment]
oh, sorry

**Comment by eed3si9n** [comment]
According to sbt/sbt#2217, there had been some misconfiguration of redirection (https to http) at JCenter, and it's now fixed. Could you try sbt 0.13.9 and see if it works?

**Comment by NoriakiHoriuchi** [comment]
OK, I will try it.

**Comment by seratch** [comment]
@eed3si9n The issue looks fixed now (#2). Thank you for your help.

**Pull request merged**
